// The city project's logic.mjs, generated alongside scene.ssdl.
//
// It is the page half of the city: it answers taps (City.select) by asking the local city service
// what the tapped BUSINESS object is, and it plays a run back by writing instance rows. It owns no
// city state of its own -- everything it shows it has just read from the service, so a page reload
// resumes rather than restarts, and a second browser shows the same numbers.
export function cityLogicSource() {
  return `// Generated by ssworld city. Re-generated on every city command; edit the city, not this file.
const PROJECT = new URL(".", import.meta.url).pathname.split("/").filter(Boolean).pop();
const BASE = "/__ssworld/city";
const POLL_MS = 500;

async function ask(route, params) {
  const query = new URLSearchParams({ project: PROJECT, ...params });
  const response = await fetch(\`\${BASE}/\${route}?\${query}\`, { cache: "no-store" });
  if (!response.ok) throw new Error(\`\${route} failed (\${response.status})\`);
  return response.json();
}

function panel() {
  let node = document.getElementById("city-panel");
  if (node) return node;
  // The template's control panel is load-bearing (the runtime writes #logical-state and #hint into
  // it), so the city panel is APPENDED next to it and never replaces it.
  const host = document.querySelector(".control-panel") || document.body;
  node = document.createElement("article");
  node.id = "city-panel";
  node.className = "view-note";
  node.innerHTML = '<div class="section-label"><span>03 / CITY</span><b>selection</b></div>'
    + '<h3 id="city-title">no object selected</h3>'
    + '<p id="city-body">Tap a building, parcel, portal or shelter.</p>'
    + '<pre id="city-detail" style="white-space:pre-wrap;font-size:11px;max-height:190px;overflow:auto;margin:0"></pre>'
    + '<p id="city-run" style="font-size:11px;opacity:.75"></p>';
  host.appendChild(node);
  return node;
}

function show(title, body, detail) {
  panel();
  document.getElementById("city-title").textContent = title;
  document.getElementById("city-body").textContent = body;
  document.getElementById("city-detail").textContent = detail ?? "";
}

export function createHostInterfaces(api) {
  let stop = false;
  let run = null;
  let cursor = 0;
  let batchError = null;

  const writeNumber = (name, value) => { try { api.logical.write(name, value); } catch (_) {} };

  async function select(objectId, kind) {
    api.logical.write("selectedId", String(objectId));
    api.logical.write("selectedKind", String(kind));
    show(\`\${kind} · \${objectId}\`, "reading…", "");
    try {
      const answer = await ask("query", { id: objectId });
      const object = answer.object || {};
      const lines = [];
      for (const [key, value] of Object.entries(object)) {
        if (["geometry", "provenance", "bbox", "polyline"].includes(key)) continue;
        lines.push(\`\${key}: \${typeof value === "object" ? JSON.stringify(value) : value}\`);
      }
      if (answer.relations && Object.keys(answer.relations).length) lines.push(\`relations: \${JSON.stringify(answer.relations)}\`);
      if (answer.impact?.length) lines.push(\`impact: \${JSON.stringify(answer.impact)}\`);
      if (answer.data_gaps?.length) lines.push(\`data gaps: \${answer.data_gaps.map((gap) => \`\${gap.field} (\${gap.reason})\`).join("; ")}\`);
      const quality = object.provenance?.quality_status ?? "unknown";
      show(\`\${answer.kind} · \${objectId}\`, \`source: \${object.provenance?.source_file ?? "?"} · quality: \${quality} · revision \${answer.revision}\`, lines.join("\\n"));
    } catch (error) {
      show(\`\${kind} · \${objectId}\`, \`could not read the city service: \${error.message}\`, "");
    }
  }

  // Playback: the run is computed by the city service; the page only samples it. Sampling never
  // feeds back, so a slow page shows fewer frames, not different traffic.
  async function tick() {
    if (stop) return;
    try {
      const status = await ask("run_frame", { cursor: String(cursor) });
      if (status.run_id) {
        // A NEW run plays from its OWN first sample. Inheriting the cursor from the previous run
        // opens a shorter run already finished -- run_frame clamps the index, so the page would show
        // the last frame of a run it never played. (Only visible when a run starts without the scene
        // being regenerated, because a hot reload resets this module and hides it.)
        if (run && run.run_id !== status.run_id) {
          cursor = 0;
          run = { run_id: status.run_id };
          setTimeout(tick, POLL_MS);
          return;
        }
        run = status;
        cursor = status.next_cursor ?? 0;
        writeNumber("simTime", status.t_s ?? 0);
        writeNumber("arrived", status.counts?.arrived ?? 0);
        writeNumber("enRoute", (status.counts?.traversing ?? 0) + (status.counts?.queued ?? 0));
        writeNumber("strandedCount", status.counts?.stranded ?? 0);
        api.logical.write("runId", String(status.run_id));
        if (Array.isArray(status.positions) && status.batch) {
          // Only the rows there actually are: padding an empty batch out to a fixed length puts
          // hundreds of markers in one spot, and a display layer that cannot be written must SAY so
          // rather than be swallowed -- a silent catch here once hid the whole layer being refused.
          const rows = status.positions.slice(0, status.batch.rows);
          try { api.instances.set(status.batch.id, { positions: rows }); batchError = null; }
          catch (error) { batchError = error.message; }
        }
        const element = document.getElementById("city-run");
        if (element) {
          element.textContent = \`run \${status.run_id} · t=\${status.t_s}s · arrived \${status.counts?.arrived ?? 0}\`
            + \` · en route \${(status.counts?.traversing ?? 0) + (status.counts?.queued ?? 0)}\`
            + \` · stranded \${status.counts?.stranded ?? 0}\${status.closed ? " · finished" : ""}\`
            + (batchError ? \` · display layer refused: \${batchError}\` : "");
        }
      }
    } catch (_) {
      // No city service (static hosting): the scene still stands, nothing animates.
    }
    setTimeout(tick, POLL_MS);
  }
  panel();
  tick();

  return { City: { select({ objectId, kind }) { void select(objectId, kind); } } };
}
`;
}
