// CityModel -> scene.ssdl. The display is REGENERATED from the model, never hand-edited alongside
// it: a city whose picture and whose numbers can drift apart is worse than one with no picture.
//
// Everything is in the same local metres the model uses, with the scene origin at the site centre so
// a 1 km site spans -500..500 instead of 0..1000. Elevations go in as they are: local z is the
// dataset's own vertical datum, which keeps a water level of 11 m readable as "11" in the source.
import { TerrainGrid, bboxOf, mm } from "./geo.mjs";

export const SCENE_SCHEMA = "SSWorldCityScene/1";

/** SSDL identifiers are [A-Za-z_][A-Za-z0-9_]*, business ids are not. The map between them is kept
 *  in the manifest so a tap on a node can answer with the BUSINESS id. */
export const nodeIdFor = (id) => `n_${String(id).replace(/[^A-Za-z0-9_]/g, "_")}`;

const PALETTE = {
  terrain: "#8f9b70",
  water: "#2f6f9fb0",
  road: "#6d6f70",
  access: "#8d8f90",
  closed: "#d64545",
  portal: "#f2b134",
  portalClosed: "#8a7a5c",
  hazard: "#c25b3ab0",
  shelter: "#2f9e6f",
  building: "#d8d2c8",
  buildingFlooded: "#7fa3c4",
  buildingExposed: "#c98a6a",
  buildingReplaced: "#e8c07d",
  landUse: { residential: "#c9b9a6", commercial: "#b8c2d6", park: "#7fb069", mixed: "#cbb7d6", industrial: "#b0a39b" },
};

const list = (values) => `[${values.join(", ")}]`;
const pair = (point) => `[${mm(point[0])}, ${mm(point[1])}]`;
const triple = (point) => `[${mm(point[0])}, ${mm(point[1])}, ${mm(point[2])}]`;

/** Drop the closing duplicate point GeoJSON rings carry; SSDL rings are implicitly closed. */
function openRing(ring) {
  if (ring.length > 1 && ring[0][0] === ring[ring.length - 1][0] && ring[0][1] === ring[ring.length - 1][1]) return ring.slice(0, -1);
  return ring;
}

function shift(ring, origin) {
  return ring.map(([x, y]) => [x - origin[0], y - origin[1]]);
}

/** Ensure counter-clockwise winding: Roof and the extruders both want ccw outlines. */
function ccw(ring) {
  let sum = 0;
  for (let i = 0; i < ring.length; i += 1) {
    const [x1, y1] = ring[i], [x2, y2] = ring[(i + 1) % ring.length];
    sum += x1 * y2 - x2 * y1;
  }
  return sum >= 0 ? ring : [...ring].reverse();
}

export function sceneOrigin(model) {
  const extent = model.frame?.extent_m;
  if (extent && extent.length === 4) return [(extent[0] + extent[2]) / 2, (extent[1] + extent[3]) / 2];
  const site = model.objects.site[0];
  if (site) { const [minX, minY, maxX, maxY] = site.bbox; return [(minX + maxX) / 2, (minY + maxY) / 2]; }
  return [0, 0];
}

/**
 * Build scene.ssdl plus the manifest that maps SSDL node ids back to business ids.
 *
 * @param options.flood       a FloodField (optional) -- its wet runs become the water surface
 * @param options.impact      an ImpactState (optional) -- closed edges are drawn as closed
 * @param options.hazards     active hazard extents to draw
 * @param options.assets      building id -> replacement asset from building.replace_asset
 * @param options.travellers  how many instance rows to reserve for the moving display layer
 */
export function buildScene(model, {
  flood = null, impact = null, hazards = [], assets = {}, travellers = 480, title = "city", revision = "rev-0000",
} = {}) {
  const origin = sceneOrigin(model);
  const lines = [];
  const idMap = {};
  const remember = (nodeId, businessId, kind) => { idMap[nodeId] = { id: businessId, kind }; return nodeId; };
  const out = (line) => lines.push(line);

  const extent = model.frame?.extent_m ?? [0, 0, 1000, 1000];
  const span = Math.max(extent[2] - extent[0], extent[3] - extent[1]);

  out("Scene {");
  out("  id: main");
  out(`  // generated by ssworld city ${SCENE_SCHEMA} from ${model.dataset?.id ?? "dataset"} at ${revision}`);
  out("  // Do not hand-edit: ssworld_city_command regenerates this file from the city model.");
  out(`  property string cityRevision: ${JSON.stringify(revision)}`);
  out('  property string selectedId: ""');
  out('  property string selectedKind: ""');
  out('  property string runId: ""');
  out("  property real simTime: 0");
  out("  property real arrived: 0");
  out("  property real enRoute: 0");
  out("  property real strandedCount: 0");
  out(`  property real waterLevel: ${flood?.bodies?.[0]?.level_m ?? model.objects.water[0]?.baseline_level_m ?? 0}`);
  out('  property string sceneDateTime: "2026-06-21T10:00:00+08:00"');
  out("  Environment { id: sky; dateTime: main.sceneDateTime; timeScale: 0 }");
  out(`  CameraView { id: overview; position: [${mm(-span * 0.55)}, ${mm(-span * 0.7)}, ${mm(span * 0.55)}]; lookAt: [0, 0, 12]; fov: 55 }`);
  out(`  CameraView { id: riverView; position: [${mm(-span * 0.12)}, ${mm(-span * 0.35)}, 90]; lookAt: [${mm(0)}, 0, 11]; fov: 50 }`);
  out("  Camera { id: mainCamera; initialView: overview }");

  // --- terrain --------------------------------------------------------------------------------
  if (model.terrain) {
    const { width, height, cell_size_m } = model.terrain;
    const columns = width, rows = height;
    const heights = cornerHeights(model.terrain, columns, rows);
    const centre = [extentCentre(model.terrain, 0) - origin[0], extentCentre(model.terrain, 1) - origin[1]];
    out(`  HeightField { id: ${remember("terrain", "terrain_grid", "terrain")}; width: ${width * cell_size_m}; depth: ${height * cell_size_m};`
      + ` columns: ${columns}; rows: ${rows}; position: [${mm(centre[0])}, ${mm(centre[1])}, 0]; color: "${PALETTE.terrain}";`
      + ` heights: ${list(heights)} }`);
  }

  // --- parcels (thin slabs so land use is readable from above) ---------------------------------
  for (const parcel of model.objects.parcels) {
    const ring = ccw(shift(openRing(parcel.geometry.coordinates[0]), origin));
    const colour = PALETTE.landUse[parcel.land_use] ?? "#bdb6ab";
    const nodeId = remember(nodeIdFor(parcel.id), parcel.id, "parcel");
    out(`  ExtrudedPolygon { id: ${nodeId}; outer: ${list(ring.map(pair))}; height: 0.4; cap: true;`
      + ` position: [0, 0, ${mm(groundAt(model, parcel.centroid) ?? 0)}]; color: "${colour}"`);
    out(`    TapHandler { id: ${nodeId}_tap; onTapped: { City.select(objectId: ${JSON.stringify(parcel.id)}, kind: "parcel"); } }`);
    out("  }");
  }

  // --- roads and access links -------------------------------------------------------------------
  const blockedEdges = new Set(impact?.blockedEdgeIds() ?? []);
  for (const edge of model.network.edges) {
    if (!edge.polyline || edge.polyline.length < 2) continue;
    const isRoad = edge.kind === "road";
    const points = edge.polyline.map((point, index) => {
      const z = edge.elevation_profile_m?.length
        ? edge.elevation_profile_m[Math.min(index, edge.elevation_profile_m.length - 1)]
        : groundAt(model, point) ?? 0;
      return [point[0] - origin[0], point[1] - origin[1], z + (isRoad ? 0.45 : 0.35)];
    });
    const colour = blockedEdges.has(edge.id) ? PALETTE.closed : (isRoad ? PALETTE.road : PALETTE.access);
    const nodeId = remember(nodeIdFor(edge.id), edge.id, isRoad ? "road" : "access_link");
    out(`  Polyline { id: ${nodeId}; points: ${list(points.map(triple))}; width: ${isRoad ? 7 : 2.5}; color: "${colour}" }`);
  }

  // --- buildings -----------------------------------------------------------------------------
  const floodedBuildings = new Set((impact ? [...impact.buildings.keys()] : []).filter((id) =>
    impact.reasons("buildings", id).some((reason) => reason.cause === "flood")));
  const exposedBuildings = new Set((impact ? [...impact.buildings.keys()] : []).filter((id) =>
    impact.reasons("buildings", id).some((reason) => reason.cause === "landslide")));
  for (const building of model.objects.buildings) {
    const ring = ccw(shift(openRing(building.geometry.coordinates[0]), origin));
    const base = building.ground_elevation_m ?? groundAt(model, building.centroid) ?? 0;
    const asset = assets[building.id]?.current ?? null;
    const colour = asset ? PALETTE.buildingReplaced
      : exposedBuildings.has(building.id) ? PALETTE.buildingExposed
        : floodedBuildings.has(building.id) ? PALETTE.buildingFlooded : PALETTE.building;
    const nodeId = remember(nodeIdFor(building.id), building.id, "building");
    const nodes = asset?.nodes?.length ? asset.nodes : [{ type: "ExtrudedPolygon", role: "mass", outer: ring, height: building.height_m ?? 9 }];
    nodes.forEach((part, index) => {
      const partRing = part.outer ? ccw(shift(openRing(part.outer.map((point) => point.length === 2 ? point : [point[0], point[1]])), part.outer === ring ? [0, 0] : origin)) : ring;
      const partId = index === 0 ? nodeId : `${nodeId}_${part.role ?? index}`;
      const z = mm(base + (part.base_z ?? 0));
      if (part.type === "Roof") {
        out(`  Roof { id: ${partId}; footprint: ${list(partRing.map((point) => `[${mm(point[0])}, ${mm(point[1])}, 0]`))};`
          + ` style: "${part.style ?? "gable"}"; pitch: ${part.pitch ?? 30}; overhang: ${part.overhang ?? 0.4};`
          + ` position: [0, 0, ${z}]; color: "#8c5a44" }`);
        return;
      }
      if (part.type === "Model" && part.source) {
        out(`  Model { id: ${partId}; source: ${JSON.stringify(part.source)}; position: [${mm(building.centroid[0] - origin[0])}, ${mm(building.centroid[1] - origin[1])}, ${z}] }`);
        return;
      }
      const taper = part.taper ? `; taper: ${part.taper}` : "";
      out(`  ExtrudedPolygon { id: ${partId}; outer: ${list(partRing.map(pair))}; height: ${mm(part.height ?? building.height_m ?? 9)}; cap: true;`
        + ` position: [0, 0, ${z}]; color: "${colour}"${taper}`);
      if (index === 0) out(`    TapHandler { id: ${nodeId}_tap; onTapped: { City.select(objectId: ${JSON.stringify(building.id)}, kind: "building"); } }`);
      out("  }");
    });
  }

  // --- portals --------------------------------------------------------------------------------
  const blockedPortals = new Set(impact?.blockedPortalIds() ?? []);
  for (const portal of model.objects.portals) {
    const closed = portal.open === false || blockedPortals.has(portal.id);
    const z = (portal.elevation_m ?? groundAt(model, portal.position) ?? 0) + 1.5;
    const nodeId = remember(nodeIdFor(portal.id), portal.id, "portal");
    out(`  Box { id: ${nodeId}; width: 3; depth: 3; height: 3; position: [${mm(portal.position[0] - origin[0])}, ${mm(portal.position[1] - origin[1])}, ${mm(z)}];`
      + ` color: "${closed ? PALETTE.portalClosed : PALETTE.portal}"`);
    out(`    TapHandler { id: ${nodeId}_tap; onTapped: { City.select(objectId: ${JSON.stringify(portal.id)}, kind: "portal"); } }`);
    out("  }");
  }

  // --- shelters -------------------------------------------------------------------------------
  for (const shelter of model.objects.shelters) {
    const z = (groundAt(model, shelter.position) ?? 0) + 3;
    const nodeId = remember(nodeIdFor(shelter.id), shelter.id, "shelter");
    out(`  Cylinder { id: ${nodeId}; radius: 8; height: 6; position: [${mm(shelter.position[0] - origin[0])}, ${mm(shelter.position[1] - origin[1])}, ${mm(z)}]; color: "${PALETTE.shelter}"`);
    out(`    TapHandler { id: ${nodeId}_tap; onTapped: { City.select(objectId: ${JSON.stringify(shelter.id)}, kind: "shelter"); } }`);
    out("  }");
  }

  // --- hazard extents --------------------------------------------------------------------------
  for (const hazard of hazards) {
    const ring = ccw(shift(openRing(hazard.geometry.coordinates[0]), origin));
    const nodeId = remember(nodeIdFor(hazard.id), hazard.id, "hazard");
    out(`  ExtrudedPolygon { id: ${nodeId}; outer: ${list(ring.map(pair))}; height: 26; cap: true;`
      + ` position: [0, 0, ${mm(groundAt(model, hazard.centroid) ?? 0)}]; color: "${PALETTE.hazard}"`);
    out(`    TapHandler { id: ${nodeId}_tap; onTapped: { City.select(objectId: ${JSON.stringify(hazard.id)}, kind: "hazard"); } }`);
    out("  }");
  }

  // --- water surface --------------------------------------------------------------------------
  // One mesh of quads at each run's own surface elevation, so a flooded terrace and a channel do not
  // get averaged into one plane. Rebuilt whenever the level changes; there is no dynamic height field.
  if (flood) {
    const runs = flood.wetRuns();
    if (runs.length) {
      const vertices = [], faces = [];
      for (const [x0, y0, x1, y1, surface] of runs) {
        const base = vertices.length / 3;
        for (const [x, y] of [[x0, y0], [x1, y0], [x1, y1], [x0, y1]]) {
          vertices.push(mm(x - origin[0]), mm(y - origin[1]), mm(surface));
        }
        faces.push(base, base + 1, base + 2, base, base + 2, base + 3);
      }
      out(`  Mesh { id: ${remember("waterSurface", "water_surface", "water")}; vertices: ${list(vertices)}; faces: ${list(faces)}; color: "${PALETTE.water}" }`);
    }
  }

  // --- moving display layer ---------------------------------------------------------------------
  // The page's logic.mjs writes live positions into this batch. `positions: []` is not a placeholder
  // for "fill it in later": an explicit batch that ships ROWS is a FIXED placement and the runtime
  // refuses setRows on it, so the only way to have a writable batch is to declare it empty.
  if (travellers > 0) {
    // Sized to be VISIBLE over a kilometre-wide site, not to be life-size: at 1.2 m a walker is one
    // pixel from the overview camera and the moving layer reads as noise.
    out("  Capsule { id: travellerShape; radius: 3; height: 12; segments: 8; position: [0, 0, -400]; color: \"#e4572e\" }");
    out("  Prefab { id: travellerPrefab; source: travellerShape }");
    out('  Instances { id: travellerBatch; prefab: travellerPrefab; placement: "explicit"; positions: [] }');
  }

  out("}");
  return {
    schema_version: SCENE_SCHEMA,
    source: `${lines.join("\n")}\n`,
    origin_m: origin,
    node_ids: idMap,
    // rows is the CEILING the page may write, not a count of rows the scene ships; the batch is empty
    // until a run drives it. 512 is the engine's per-batch instance limit.
    traveller_batch: travellers > 0 ? { id: "travellerBatch", rows: Math.min(travellers, 512) } : null,
    palette: PALETTE,
  };
}

function extentCentre(terrain, axis) {
  return terrain.origin_sw_m[axis] + (axis === 0 ? terrain.width : terrain.height) * terrain.cell_size_m / 2;
}

function cornerHeights(terrain, columns, rows) {
  const out = [];
  const { width, height, values } = terrain;
  for (let r = 0; r <= rows; r += 1) {
    for (let c = 0; c <= columns; c += 1) {
      // Corner (c, r) averages the up-to-four cells that meet there; the border clamps.
      let sum = 0, count = 0;
      for (const [dc, dr] of [[-1, -1], [0, -1], [-1, 0], [0, 0]]) {
        const col = Math.min(width - 1, Math.max(0, c + dc));
        const row = Math.min(height - 1, Math.max(0, r + dr));
        const value = values[row][col];
        if (value === terrain.nodata) continue;
        sum += value; count += 1;
      }
      out.push(count ? mm(sum / count) : 0);
    }
  }
  return out;
}

const terrainCache = new WeakMap();

/** Bilinear, not nearest-cell: the grid holds CELL-CENTRE samples, so a slope read at the nearest
 *  centre steps by half a cell and a building placed on it visibly floats or sinks. */
function groundAt(model, point) {
  if (!model.terrain || !point) return null;
  if (!terrainCache.has(model.terrain)) {
    terrainCache.set(model.terrain, new TerrainGrid({ ...model.terrain, values: model.terrain.values, row_order: model.terrain.row_order }));
  }
  return terrainCache.get(model.terrain).sample(point[0], point[1]);
}

export const CITY_HOST_INTERFACES = {
  City: { methods: { select: { args: [{ name: "objectId", type: "string" }, { name: "kind", type: "string" }] } } },
};

export { PALETTE as CITY_PALETTE, groundAt as terrainAt };
