const titles=['街区鸟瞰','全范围鸟瞰','道路近景','过街路口','北向总图','滨河'];
const captions=['秋日午后 · 示意住宅与庭院 · 真实路网','真实路网 · 同源街区 · 保留数据空缺','连续路面 · 圆角路缘 · 人行道铺装','实源过街位置 · 标线裁切 · 步行衔接','检查路网边界与地块关系','真实水体轮廓 · 河床与水面材质'];
let mode=0;
function displayView(next){mode=next;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.view===mode)));document.getElementById('view-index').textContent=`0${mode+1} / 0${titles.length}`;document.getElementById('view-title').textContent=titles[mode];document.getElementById('view-description').textContent=captions[mode];}
function setView(next){if(!window.SSWorld?.logical)return;window.SSWorld.logical.write('viewMode',next);window.SSWorld.recallView?.();displayView(next);}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(+b.dataset.view));
document.getElementById('reset-view').onclick=()=>setView(mode);
document.querySelectorAll('[data-property]').forEach(el=>el.onchange=()=>window.SSWorld?.logical?.write(el.dataset.property,el.checked));
for(const key of ['info','map']){const d=document.getElementById(key);document.getElementById(key+'-toggle').onclick=()=>d.showModal();d.querySelector('.close').onclick=()=>d.close();}
document.getElementById('time-slider').oninput=e=>{const hour=+e.target.value;const value=`${String(Math.floor(hour)).padStart(2,'0')}:${String(Math.round((hour%1)*60)).padStart(2,'0')}`;document.getElementById('time-value').textContent=value;const current=window.SSWorld?.logical?.read().properties.sceneDateTime||'2026-11-05T16:15:00+08:00';window.SSWorld?.logical?.writeBatch({timeOfDay:hour,sceneDateTime:`${current.slice(0,11)}${value}:00${current.slice(19)}`});};
fetch('report.json').then(r=>r.json()).then(r=>{document.getElementById('stat-roads').textContent=r.counts.roads;document.getElementById('stat-blocks').textContent=r.counts.blocks;if(r.counts.water_planes===0)document.querySelector('[data-view="5"]').hidden=true;});
setInterval(()=>{const state=document.body.dataset.runtime;document.getElementById('loading').hidden=state==='ready';document.getElementById('live-state').textContent=state==='ready'?'WebGPU · 实时场景':state==='error'?'加载失败':'正在加载';if(state==='error')document.querySelector('#loading b').textContent='加载失败，请查看运行日志';if(state==='ready'&&window.SSWorld?.logical){const p=window.SSWorld.logical.read().properties;if(p.viewMode!==mode)displayView(p.viewMode);document.querySelectorAll('[data-property]').forEach(el=>el.checked=!!p[el.dataset.property]);}},400);
document.getElementById('project-coordinates').onclick=async()=>{const el=document.getElementById('projection-message');try{el.textContent='正在调用 SSEngine 原生 API…';const {runProjection}=await import('./engine-project.mjs');const result=await runProjection(window.SSmap);el.textContent=`已转换 ${result.unique_points} 个坐标；往返误差 ${result.max_roundtrip_error_m.toExponential(2)} 米。现在可重新运行生成脚本。`;}catch(e){el.textContent='转换失败：'+e.message+'。请确认 --serve-projection 服务正在运行。';}};
